---
Name: app
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Dribbles\Site\Extensions\SiteConfigExtension

UndefinedOffset\NoCaptcha\Forms\NocaptchaField:
    site_key: "6Lc6NV4UAAAAAMK8pwT1nCHTIYAbPC2h1dCjFCrq" #Your site key (required)
    secret_key: "6Lc6NV4UAAAAADJz9-4wjQg8am9izHgTB-1ga-RK" #Your secret key (required)
    verify_ssl: true #Allows you to disable php-curl's SSL peer verification by setting this to false (optional, defaults to true)
    default_theme: "light" #Default theme color (optional, light or dark, defaults to light)
    default_type: "image" #Default captcha type (optional, image or audio, defaults to image)
    default_size: "normal" #Default size (optional, normal, compact or invisible, defaults to normal)
    default_badge: "bottomright" #Default badge position (bottomright, bottomleft or inline, defaults to bottomright)
    proxy_server: "" #Your proxy server address (optional)
    proxy_auth: "" #Your proxy server authentication information (optional)
UserForm:
  extensions:
    - MyFormDecorator
